version: "3.1"
services:
    myhello:
        image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        command:
            - "--entrypoints.web.address=:80"
        expose:
            - "80"
        labels:        
            - "traefik.http.routers.myhello.rule=PathPrefix(`/myhello`)"
            - "traefik.http.routers.myhello-route.entrypoints=web"
            - "traefik.http.middlewares.myhello-pathstrip.stripprefixregex.regex=/myhello"
            - "traefik.http.routers.myhello.middlewares=myhello-pathstrip@docker"
            - "traefik.enable=true"
